"use client";

import { useEffect, useMemo, useRef, useState } from "react";

/**
 * BrandScroller — a simple, flat horizontal marquee of company LOGOS only.
 * Auto-scrolls slowly; disappears when the user starts a search (controlled by
 * the `visible` prop from the parent).
 *
 * It loads EVERY image listed in /brands/manifest.json, which is generated by
 * scripts/gen-brand-manifest.mjs. Drop any logo into /public/brands and run the
 * generator to include it — no code changes needed.
 */

export default function BrandScroller({ visible }: { visible: boolean }) {
  const trackRef = useRef<HTMLDivElement>(null);
  const [logos, setLogos] = useState<string[]>([]);

  useEffect(() => {
    fetch("/brands/manifest.json")
      .then((r) => (r.ok ? r.json() : { logos: [] }))
      .then((d) => setLogos(Array.isArray(d.logos) ? d.logos : []))
      .catch(() => setLogos([]));
  }, []);

  // Duplicate the list so the marquee loops seamlessly (only once loaded).
  const loop = useMemo(() => [...logos, ...logos], [logos]);

  // Pause animation while hovered for readability.
  useEffect(() => {
    const track = trackRef.current;
    if (!track) return;
    const slow = () => track.style.setProperty("--scroll-duration", "240s");
    const normal = () => track.style.setProperty("--scroll-duration", "120s");
    track.addEventListener("mouseenter", slow);
    track.addEventListener("mouseleave", normal);
    return () => {
      track.removeEventListener("mouseenter", slow);
      track.removeEventListener("mouseleave", normal);
    };
  }, []);

  if (loop.length === 0) return null;

  return (
    <div
      className={`brand-scroller${visible ? " is-visible" : " is-hidden"}`}
      aria-hidden={!visible}
    >
      <div className="brand-scroller-viewport">
        <div className="brand-track" ref={trackRef}>
          {loop.map((src, i) => (
            <div className="brand-item" key={`${src}-${i}`}>
              <div className="brand-logo-card">
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                  src={src}
                  alt=""
                  className="brand-logo-img"
                  loading="lazy"
                />
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
